version: '3'
services:

  # Proxy Services
  proxy:
    image: nginx:${NGINX_VERSION}-alpine
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ./docker/logs/proxy:/var/log/nginx
      - ./docker/services/proxy/common:/etc/nginx/conf.d/common
      - ./docker/services/proxy/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - nginx-api
      - nginx-front

  # API Services
  nginx-api:
    image: nginx:${NGINX_VERSION}-alpine
    expose:
      - "80"
    volumes:
      - ${PATH_API_SRC}:/var/www/html
      - ./docker/logs/nginx-api:/var/log/nginx
      - ./docker/services/nginx-api/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./docker/services/php-fpm
      args:
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
        - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
    volumes:
      - ./docker/services/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ${PATH_API_SRC}:/var/www/html
    expose:
      - "9000"

  # Front Services
  nginx-front:
    image: nginx:${NGINX_VERSION}-alpine
    expose:
      - "80"
    volumes:
      - ${PATH_FRONT_SRC}:/var/www/html
      - ./docker/logs/nginx-front:/var/log/nginx
      - ./docker/services/nginx-front/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
