version: '3'
services:

  ### Proxy Service ###############################################################
  proxy:
    environment:
      - TZ=${GENERAL_TIMEZONE}
    depends_on:
      - nginx-api
      - nginx-front
      - mailcatcher
      - redis-commander
    image: jwilder/nginx-proxy
    ports:
      - "${PROXY_HOST_HTTP_PORT}:80"
    restart: always
    volumes:
      - ./docker/logs/proxy:/var/log/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro

  #### API Service ################################################################
  nginx-api:
    environment:
      - TZ=${GENERAL_TIMEZONE}
      - VIRTUAL_HOST=${API_VIRTUAL_HOST}
      - VIRTUAL_PORT=80
    depends_on:
      - php-fpm
      - mssql
    image: nginx:${NGINX_VERSION}-alpine
    ports:
      - "${API_HOST_HTTP_PORT}:80"
    restart: always
    volumes:
      - ${PATH_API_SRC}:/var/www/html
      - ./docker/logs/nginx-api:/var/log/nginx
      - ./docker/services/nginx-api/default.conf:/etc/nginx/conf.d/default.conf
      
  php-fpm:
    build:
      context: ./docker/services/php-fpm
      args:
        - VERSION=${PHP_FPM_VERSION}
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
        - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
    environment:
      - TZ=${GENERAL_TIMEZONE}
    expose:
      - "9000"
    volumes:
      - ./docker/logs/php-fpm:/var/log/php-fpm
      - ./docker/services/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ${PATH_API_SRC}:/var/www/html

  ### Front Service ###############################################################
  nginx-front:
    environment:
      - TZ=${GENERAL_TIMEZONE}
      - VIRTUAL_HOST=${FRONT_VIRTUAL_HOST}
      - VIRTUAL_PORT=80
    image: nginx:${NGINX_VERSION}-alpine
    ports:
      - "${FRONT_HOST_HTTP_PORT}:80"
    restart: always
    volumes:
      - ${PATH_FRONT_SRC}:/var/www/html
      - ./docker/logs/nginx-front:/var/log/nginx
      - ./docker/services/nginx-front/default.conf:/etc/nginx/conf.d/default.conf

  ### MSSQL Service ###############################################################
  mssql:
    build:
      context: ./docker/services/mssql
    environment:
      - TZ=${GENERAL_TIMEZONE}
      - ACCEPT_EULA=Y
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "${MSSQL_HOST_PORT}:1433"
    volumes:
    # - ./docker/services/mssql/data:/var/opt/mssql
      - ./docker/logs/mssql:/var/opt/mssql/log
      
  ### Fake SMTP Service ###########################################################
  mailcatcher:
    environment:
        - TZ=${GENERAL_TIMEZONE}
        - VIRTUAL_HOST=${MAILCATCHER_CLIENT_VIRTUAL_HOST}
        - VIRTUAL_PORT=1080
    image: schickling/mailcatcher:latest
    ports:
      - "${MAILCATCHER_CLIENT_HOST_HTTP_PORT}:1080"
  
  ### Cache Service ###############################################################
  redis:
    build: ./docker/services/redis
    environment:
      - TZ=${GENERAL_TIMEZONE}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    restart: always
    volumes:
      - ./docker/data/redis:/data
      
  redis-commander:
    environment:
      - TZ=${GENERAL_TIMEZONE}
      - REDIS_HOSTS=redis:6379
      - VIRTUAL_HOST=${REDIS_COMMANDER_VIRTUAL_HOST}
      - VIRTUAL_PORT=8081
    depends_on:
      - redis
    image: rediscommander/redis-commander:latest
    ports:
      - "${REDIS_COMMANDER_HOST_HTTP_PORT}:8081"
    restart: always
    
  ### SQL Server GUI Service ######################################################
  adminer:
    build:
      context: ./docker/services/adminer
    depends_on:
      - mssql
    environment:
      - TZ=${GENERAL_TIMEZONE}
      - VIRTUAL_HOST=${ADMINER_VIRTUAL_HOST}
      - VIRTUAL_PORT=8080
    ports:
      - "${ADMINER_HOST_PORT}:8080"
    
