version: '3'
services:

  # Proxy Service
  proxy:
    environment:
      - TZ=${GENERAL_TIMEZONE}
    image: nginx:${NGINX_VERSION}-alpine
    ports:
      - "${PROXY_HOST_HTTP_PORT}:80"
    volumes:
      - ./docker/logs/proxy:/var/log/nginx
      - ./docker/services/proxy/common:/etc/nginx/conf.d/common
      - ./docker/services/proxy/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - nginx-api
      - nginx-front

  # API Service
  nginx-api:
    environment:
      - TZ=${GENERAL_TIMEZONE}
    image: nginx:${NGINX_VERSION}-alpine
    expose:
      - "80"
    volumes:
      - ${PATH_API_SRC}:/var/www/html
      - ./docker/logs/nginx-api:/var/log/nginx
      - ./docker/services/nginx-api/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php-fpm
  php-fpm:
    environment:
      - TZ=${GENERAL_TIMEZONE}
    build:
      context: ./docker/services/php-fpm
      args:
        - VERSION=${PHP_FPM_VERSION}
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
        - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
    volumes:
      - ./docker/logs/php-fpm:/var/log/php-fpm
      - ./docker/services/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ${PATH_API_SRC}:/var/www/html
    expose:
      - "9000"

  # Front Service
  nginx-front:
    environment:
      - TZ=${GENERAL_TIMEZONE}
    image: nginx:${NGINX_VERSION}-alpine
    expose:
      - "80"
    volumes:
      - ${PATH_FRONT_SRC}:/var/www/html
      - ./docker/logs/nginx-front:/var/log/nginx
      - ./docker/services/nginx-front/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  # MSSQL Service
  mssql:
    build:
      context: ./docker/services/mssql
    environment:
      - TZ=${GENERAL_TIMEZONE}
      - ACCEPT_EULA=Y
      - MSSQL_PID=${MSSQL_PID}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
#      - ./docker/services/mssql/data:/var/opt/mssql
      - ./docker/logs/mssql:/var/opt/mssql/log
    ports:
      - "${MSSQL_HOST_PORT}:1433"
